import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import Image from 'next/image';

import About from '../components/about';
import Listings from '../components/listings';
import Services from '../components/services';
import Testimonial from '../components/testimonial';
import Form from '../components/form';
import scrollIcon from '../assets/icons/up-arrow.png';

import Footer from '@/components/footer';
import Hero from '@/components/hero';

const HomePage = () => {
  const [showButton, setShowButton] = useState(false);

  const handleScrollToTop = () => {
    window.scrollTo({ top: (0, 0), behavior: 'smooth' });
  };

  useEffect(() => {
    const handleScroll = () => {
      if (window.pageYOffset > 500) {
        setShowButton(true);
      } else {
        setShowButton(false);
      }
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Jamie Liu | FIRST CLASS STARLINK REALTY Brokerage </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dark:bg-bgDark">
        <Hero
         address="200 TOWN CENTRE BLVD #105
         Markham ON L3R 8G5"
         phone="905-604-1010"
         email="jamieliurealtorgta@gmail.com"/>
         <About
          cardTitle1="10+ years"
          cardSubText1="investment experience"
          cardTitle2="200+"
          cardSubText2="satisfied customers"
          cardTitle3="300+"
          cardSubText3="transactions"
        />
        
       
        <Services />
        <Listings />

        
        <Testimonial />
        <Form />
        <Footer />
        {showButton && (
          <div className="fixed bottom-24 right-10 z-50">
            <button
              onClick={handleScrollToTop}
              className="overflow-visible"
            >
              <Image src={scrollIcon} alt="scroll button" className="w-[45px] h-[45px]" />
            </button>
          </div>
        )}
      </div>
    </>
  );
};

export default HomePage;
